import { useEffect } from 'react';
import { useKioskStore } from '../store/useKioskStore';
import { remoteTranslationService } from '../services/remoteTranslationService';

const skip=(n)=>{const p=n.parentElement;if(!p)return true;if(p.closest('[data-no-translate],script,style,textarea,input,code,pre'))return true;const v=n.nodeValue?.replace(/\s+/g,' ').trim();return !v||v.length<2||v.length>220||/^[\d\s+().:/#%₹,-]+$/.test(v)||/^https?:\/\//i.test(v)};
export default function useDomTranslation(){
 const language=useKioskStore(s=>s.language||'en');
 useEffect(()=>{if(language==='en')return;let cancelled=false,timer;const translated=new WeakSet();const attrs=new WeakMap();const run=async()=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];let n;while((n=walker.nextNode()))if(!translated.has(n)&&!skip(n))nodes.push(n);const attr=[...document.querySelectorAll('[placeholder],[aria-label],[title]')].flatMap(el=>['placeholder','aria-label','title'].filter(a=>el.getAttribute(a)).map(a=>({el,a,text:el.getAttribute(a)}))).filter(x=>!attrs.get(x.el)?.has(x.a));const items=[...nodes.map(node=>({node,text:node.nodeValue.replace(/\s+/g,' ').trim()})),...attr.map(x=>({attr:x,text:x.text.trim()}))].slice(0,80);let i=0;const worker=async()=>{while(!cancelled){const item=items[i++];if(!item)return;const text=item.text;const translatedText=remoteTranslationService.getCachedTranslation(text,language)||await remoteTranslationService.ensureTranslation(text,language);if(cancelled)return;if(item.node&&item.node.isConnected){item.node.nodeValue=translatedText;translated.add(item.node)}if(item.attr&&item.attr.el.isConnected){item.attr.el.setAttribute(item.attr.a,translatedText);let set=attrs.get(item.attr.el);if(!set){set=new Set();attrs.set(item.attr.el,set)}set.add(item.attr.a)}}};await Promise.all(Array.from({length:5},worker));};const schedule=()=>{clearTimeout(timer);timer=setTimeout(run,120)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true});return()=>{cancelled=true;clearTimeout(timer);observer.disconnect()}},[language]);
}
