import React,{useEffect,useState} from 'react';
import { Leaf, Stethoscope, Loader2 } from 'lucide-react';
import { kioskApi,getErrorMessage } from '../services/api';
import { useKioskStore } from '../store/useKioskStore';
import { useTranslation } from '../hooks/useTranslation';
export default function Screen3_DepartmentSelector(){
 const {sessionData,updateSession,nextScreen}=useKioskStore(); const {t}=useTranslation();
 const pathway=sessionData.pathway||'allopathy'; const [departments,setDepartments]=useState([]); const [doctors,setDoctors]=useState([]); const [dept,setDept]=useState(sessionData.selectedDepartment?.id||''); const [doctor,setDoctor]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{setLoading(true);kioskApi.departments(pathway).then(d=>{const list=Array.isArray(d)?d:[];setDepartments(list);setDept(sessionData.selectedDepartment?.id||list[0]?.id||'')}).catch(e=>setError(getErrorMessage(e))).finally(()=>setLoading(false))},[pathway]);
 useEffect(()=>{if(!dept){setDoctors([]);return}kioskApi.doctors(dept).then(d=>setDoctors(Array.isArray(d)?d:[])).catch(()=>setDoctors([]))},[dept]);
 const go=()=>{const selected=departments.find(d=>d.id===dept);const doc=doctors.find(d=>d.id===doctor)||null;updateSession({selectedDepartment:selected||null,requestedDoctor:doc});nextScreen()};
 return <section className="screen-card"><p className="eyebrow">02 • {t('department')}</p><h2>{t('department')}</h2><p>{pathway==='ayurveda'?t('ayurveda'):t('allopathy')} pathway is selected. Choose where you would like to be routed.</p><div className="pathway-banner">{pathway==='ayurveda'?<Leaf/>:<Stethoscope/>}<strong>{pathway==='ayurveda'?t('ayurveda'):t('allopathy')}</strong><span>{pathway==='ayurveda'?t('ayurvedaDesc'):t('allopathyDesc')}</span></div><div className="form-grid compact"><label><span>{t('department')}</span><select value={dept} onChange={e=>setDept(e.target.value)} disabled={loading}><option value="">{loading?'Loading…':'Select department'}</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label><span>{t('doctor')}</span><select value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">{t('anyDoctor')}</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div>{error&&<div className="error-box">{error}</div>}<button className="primary-btn wide" disabled={!dept||loading} onClick={go}>{loading?<Loader2 className="spin"/>:t('continue')}</button></section>;
}