"""Conversation engine models for Module A — Conversational History Engine."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ConversationPhase(str, Enum):
    """Tracks which section of the clinical interview is active."""
    NOT_STARTED = "not_started"
    EMERGENCY_SCREEN = "emergency_screen"
    CHIEF_COMPLAINT = "chief_complaint"
    HPI = "hpi"
    PAST_MEDICAL = "past_medical"
    PAST_SURGICAL = "past_surgical"
    DRUG_ALLERGY = "drug_allergy"
    FAMILY_HISTORY = "family_history"
    PERSONAL_HISTORY = "personal_history"
    REVIEW_OF_SYSTEMS = "review_of_systems"
    AYUSH_DASHAVIDHA = "ayush_dashavidha"
    AYUSH_AHARA_VIHARA = "ayush_ahara_vihara"
    COMPLETED = "completed"


class QuestionType(str, Enum):
    TEXT = "text"
    CHOICE = "choice"
    NUMBER = "number"
    MULTI_SELECT = "multi_select"


class Choice(BaseModel):
    value: str
    label: str
    label_local: Optional[str] = None  # In patient's selected language


class AIQuestion(BaseModel):
    """A question generated by the AI conversation engine."""
    question_id: str
    phase: ConversationPhase
    prompt: str
    prompt_local: Optional[str] = None  # In patient's language
    helper: Optional[str] = None
    question_type: QuestionType = QuestionType.TEXT
    options: Optional[list[Choice]] = None
    selection_mode: Optional[str] = None
    is_follow_up: bool = False
    audio_base64: Optional[str] = None
    audio_encoding: Optional[str] = None
    audio_mime_type: Optional[str] = None
    tts_duration_estimate_sec: Optional[float] = None
    clinical_context: Optional[str] = Field(
        default=None,
        description="Brief clinical rationale for this question (for audit)",
    )


class ConversationStartRequest(BaseModel):
    intake_pathway: str = Field(
        default="general",
        description="'general' or 'ayush'",
    )


class PatientResponse(BaseModel):
    """Patient's answer to a question — text or touch selection."""
    question_id: str
    answer: str
    input_mode: str = Field(
        default="text",
        description="'text', 'touch', or 'speech'",
    )
    confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="ASR confidence if answer came from speech",
    )


class SpeechInput(BaseModel):
    """Metadata for a speech-based response (audio is in file upload)."""
    question_id: str
    language: str = "en"


class RedFlagAlert(BaseModel):
    """An urgent clinical alert triggered during conversation."""
    id: str
    level: str = "urgent"
    title: str
    patient_message: str
    patient_message_local: Optional[str] = None
    evidence: list[str]
    triggered_at: datetime = Field(default_factory=datetime.utcnow)


class ConversationState(BaseModel):
    """Full snapshot of the current conversation state."""
    session_id: str
    phase: ConversationPhase
    current_question: Optional[AIQuestion] = None
    answered_questions: list[dict] = Field(default_factory=list)
    red_flags: list[RedFlagAlert] = Field(default_factory=list)
    progress_percent: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
    )
    is_complete: bool = False


class ConversationTurnResponse(BaseModel):
    """Response after processing a patient answer."""
    acknowledged: bool = True
    answer_confirmed: str
    next_question: Optional[AIQuestion] = None
    red_flags: list[RedFlagAlert] = Field(default_factory=list)
    phase: ConversationPhase
    progress_percent: float
    is_complete: bool = False


class TTSRequest(BaseModel):
    """Request model for text-to-speech synthesis."""
    text: Optional[str] = None
    language: Optional[str] = "en"

